baseURL = 'https://scalar42.github.io/'
languageCode = 'en-us'
title = "Scalar42"
paginate = 5

copyright = "© Copyright 2022"

theme = 'hugo-ink'

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "I thought what I’d do was, I’d pretend I was one of those deaf-mutes."
	featherIconsCDN = true
	mode = "auto"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/scalar42"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/scalar42"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
